
sq: clean
	
	python mk-inf-sq.py \
	'C:\Users\Luke\Dropbox\Reduplication - for Luke\FULL TRANSCRIPTS-UK' 'tmpUK'

ang: clean

	python mk-inf-ang.py \
	'C:\Users\Luke\Dropbox\Reduplication - for Luke\FULL TRANSCRIPTS-UK\UK - YORK' 'tmpYORK'

clean: 
	clear
	rm -rf tmpUK tmpYORK